// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjzxjgodsxhfqntsipuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqenhqZ29kc3hoZnFudHNpcHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODk4NTMsImV4cCI6MjA2ODg2NTg1M30.D0l2ACm08_icKUwTSRBaKRcm18FRMxEIkM6IWVVnZMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});